src/Services/ResSys.AdminStatistic/src/ResSys.AdminStatistic.WebApi/Models/ErrorViewModel.cs
using System;

namespace ResSys.AdminStatistic.WebApi.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Services/ResSys.AdminStatistic/src/ResSys.AdminStatistic.WebApi/Models/MonthReservationResult.cs
using System;
using System.Collections.Generic;
using ResSys.AdminStatistic.Domain.FilmCatalog;

namespace ResSys.AdminStatistic.WebApi.Models
{
    /// <summary>
    /// A create for a month reservation to be sent to the viewmodel
    /// </summary>
    public class MonthReservationViewModel
    {
        public MonthReservationViewModel()
        {
            this.Count = new List<MonthReservationItem>();
        }
        public List<MonthReservationItem> Count { get; set; }
    }

    /// <summary>
    /// A create for a month reservation item to be sent to the viewmodel
    /// </summary>
    public class MonthReservationItem
    {
        public MonthReservationItem(int month, int number)
        {
            this.Month = month;
            this.Number = number;
        }
        public int Month { get; set; }
        public int Number { get; set; }
    }
}

src/Services/ResSys.AdminStatistic/src/ResSys.AdminStatistic.WebApi/Models/ReservationViewModel.cs
using System;
using System.Collections.Generic;
using ResSys.AdminStatistic.Domain.FilmCatalog;

namespace ResSys.AdminStatistic.WebApi.Models
{
    /// <summary>
    /// Reservation view model
    /// </summary>

    public record ReservationViewModel(Guid ReservationId, DateTime ReservedFrom, DateTime ReservedTo, List<FilmViewModel> Films, List<BookViewModel> Books);
    public record FilmViewModel(string EIDR, string Name, Guid AuthorId, int AuthorRegNum, int Amount);
    public record BookViewModel(string IBAN, string Name, Guid AuthorId, int AuthorRegNum, int Amount);
}

src/Services/ResSys.AdminStatistic/src/ResSys.AdminStatistic.WebApi/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ResSys.AdminStatistic.Application.Commands.FilmCatalog;
using ResSys.AdminStatistic.WebApi.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ResSys.AdminStatistic.WebApi.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IGetAllFilmsUseCase _userCase;

        public HomeController(ILogger<HomeController> logger, IGetAllFilmsUseCase userCase)
        {
            _logger = logger;
            _userCase = userCase;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Services/ResSys.AdminStatistic/src/ResSys.AdminStatistic.WebApi/Controllers/StatisticController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ResSys.AdminStatistic.Application.Commands.Reservations;
using ResSys.AdminStatistic.Application.Commands.Statistics;
using ResSys.AdminStatistic.WebApi.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ResSys.AdminStatistic.WebApi.Controllers
{
    [Route("statistic")]
    public class StatisticController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IGetReservationsPerMonthUseCase distributionUseCase;
        private readonly IGetReservationsUserCase reservationListUseCase;
        public StatisticController(ILogger<HomeController> logger, IGetReservationsPerMonthUseCase distributionUseCase, IGetReservationsUserCase reservationListUseCase)
        {
            _logger = logger;
            this.distributionUseCase = distributionUseCase;
            this.reservationListUseCase = reservationListUseCase;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Route("/statistic/monthDistribution")]
        public async Task<IActionResult> GetReservationMonthDates()
        {
            var data = await distributionUseCase.Execute();
            MonthReservationViewModel model = new MonthReservationViewModel();
            model.Count = data.Count.Select(x => new MonthReservationItem(x.Month, x.Number)).ToList();
            return View(model);
        }
        [Route("/statistic/reservations")]
        public async Task<IActionResult> GetReservations()
        {
            var reservationDtos = await reservationListUseCase.Execute();

            List<ReservationViewModel> reservationWMList = new List<ReservationViewModel>();

            foreach (var reservation in reservationDtos)
            {
                List<FilmViewModel> films = new List<FilmViewModel>();
                List<BookViewModel> books = new List<BookViewModel>();

                foreach (var film in reservation.Films)
                {
                    films.Add(new FilmViewModel(film.EIDR, film.Name, film.AuthorId, film.AuthorRegNum, film.Amount));
                }
                foreach (var book in reservation.Books)
                {
                    books.Add(new BookViewModel(book.IBAN, book.Name, book.AuthorId, book.AuthorRegNum, book.Amount));
                }

                ReservationViewModel reservationWM = new ReservationViewModel(
                    reservation.ReservationId, reservation.ReservedFrom, reservation.ReservedTo, films, books
                );
                reservationWMList.Add(reservationWM);
            }
            return View(reservationWMList);
        }
    }
}

src/Services/ResSys.AdminStatistic/src/ResSys.AdminStatistic.WebApi/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Statistics home page</h1>
</div>
<div>
    <p>Navigate by menu to concrete statistic and functions</p>
</div>

src/Services/ResSys.AdminStatistic/src/ResSys.AdminStatistic.WebApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="/Scripts/jquery-3.6.0.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <title>@ViewData["Title"] - ResSys.AdminStatistic.WebAppMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("scripts", required: false)
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home"
                    asp-action="Index">ResSys.Statistic.WebAppMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Statistic"
                                asp-action="GetReservations">Reservations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Statistic"
                                asp-action="GetReservationMonthDates">Month ditribution</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ResSys.AdminStatistic.WebAppMVC - <a asp-area="" asp-controller="Home"
                asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @* @RenderSection("Scripts", required: false) *@
</body>

</html>

src/Services/ResSys.AdminStatistic/src/ResSys.AdminStatistic.WebApi/Views/Statistic/GetReservationMonthDates.cshtml
@model ResSys.AdminStatistic.WebApi.Models.MonthReservationViewModel

<h3>Statistical output for number of reservations per month</h3>
<p>
    Table below shows how many reservations were made in each month together
</p>

<table id="myTable" class="table" cellspacing="0">
    <thead>
        <tr>
            <th>
                Number of month
            </th>
            <th>
                Number of reservations created
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Count)
        {
            <tr>
                <td>
                    @Html.DisplayFor(x => item.Month). month
                </td>
                <td>
                    @Html.DisplayFor(x => item.Number)
                </td>
            </tr>
        }
    </tbody>
</table>

src/Services/ResSys.AdminStatistic/src/ResSys.AdminStatistic.WebApi/Views/Statistic/GetReservations.cshtml
@model List<ResSys.AdminStatistic.WebApi.Models.ReservationViewModel>

<h3>Overview of active reservations</h3>
<p>
    Table below shows active reservations which can be deactivated. There is no
    feedback after button click, so please do refresh page after clicking 'deactivate' button.
</p>

<table id="myTable" class="table" cellspacing="0">
    <thead>
        <tr>
            <th>
                Reserved from
            </th>
            <th>
                Reserved to
            </th>
            <th>
                Number of distinct films
            </th>
            <th>
                Number of distinct books
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(x => item.ReservedFrom)
                </td>
                <td>
                    @Html.DisplayFor(x => item.ReservedTo)
                </td>
                <td>
                    @Html.DisplayFor(x => item.Films.Count)
                </td>
                <td>
                    @Html.DisplayFor(x => item.Books.Count)
                </td>
                <td>
                    <input type="submit" class="deactivate" value="Deactivate" name='@item.ReservationId'
                    id="@item.ReservationId" />
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts {

<script type="text/javascript">
    $(document).ready(function ()
    {
        $('.deactivate').click(function (e)
        {
            var xhr = new XMLHttpRequest();
            xhr.onreadystatechange = function ()
            {
                if (this.readyState == 4 && this.status == 200)
                {
                    @* There can be handlet notification for user *@
                }
            }
            xhr.open('DELETE', 'http://localhost:5025/api/deactivate/' + this.name)
            xhr.send()
        });
    });
</script>
}

src/Services/ResSys.AdminStatistic/src/ResSys.AdminStatistic.WebApi/Views/Statistic/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Statistics home page</h1>
</div>